# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotsrpc < Formula
  desc "CLI utility to generate go and typescript RPC calls easily"
  homepage "https://github.com/foomo/gotsrpc"
  version "2.3.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/gotsrpc/releases/download/v2.3.3/gotsrpc_2.3.3_darwin_amd64.tar.gz"
      sha256 "6e78025af08f6a9126f3e07e21629e12cd61e4e0638dc361c8c2863a252943b8"

      def install
        bin.install "gotsrpc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foomo/gotsrpc/releases/download/v2.3.3/gotsrpc_2.3.3_darwin_arm64.tar.gz"
      sha256 "e32cfea13c8066faf5da3fd63654b171ab7628305e247a18c09ae4b6cdfaf4d7"

      def install
        bin.install "gotsrpc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/gotsrpc/releases/download/v2.3.3/gotsrpc_2.3.3_linux_arm64.tar.gz"
      sha256 "f25b5fd931a500a6d12ea1466cfe862ae594cafb08dcfb0be8938669e9d44e05"

      def install
        bin.install "gotsrpc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/foomo/gotsrpc/releases/download/v2.3.3/gotsrpc_2.3.3_linux_amd64.tar.gz"
      sha256 "b41647738ce2c245291bfbd541e2f3c3cd2c4fc2d5a7b331eacdaf1f3db16dbe"

      def install
        bin.install "gotsrpc"
      end
    end
  end

  def caveats; <<~EOS
    gotsrpc gotsrpc.yml
  EOS
  end
end
