# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotsrpc < Formula
  desc "CLI utility to generate go and typescript RPC calls easily"
  homepage "https://github.com/foomo/gotsrpc"
  version "2.3.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/foomo/gotsrpc/releases/download/v2.3.2/gotsrpc_2.3.2_darwin_arm64.tar.gz"
      sha256 "73004bec1fad2c512c9d847d5a5be92a1c98332b908e8df647a7f6afcecfe65e"

      def install
        bin.install "gotsrpc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/foomo/gotsrpc/releases/download/v2.3.2/gotsrpc_2.3.2_darwin_amd64.tar.gz"
      sha256 "7aecb3fe5ddd1a011f80621492efbafc158892a69f485583b7db947f32c8738a"

      def install
        bin.install "gotsrpc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/gotsrpc/releases/download/v2.3.2/gotsrpc_2.3.2_linux_arm64.tar.gz"
      sha256 "018649951a24852bda434663a5b0848d43f67beec129ad79e01d6b378bb1277a"

      def install
        bin.install "gotsrpc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/foomo/gotsrpc/releases/download/v2.3.2/gotsrpc_2.3.2_linux_amd64.tar.gz"
      sha256 "bcbbe2cefceb46c8b65038f9a7b18fa3a07120f0acd4cd60dada0184f52fdc78"

      def install
        bin.install "gotsrpc"
      end
    end
  end

  def caveats; <<~EOS
    gotsrpc gotsrpc.yml
  EOS
  end
end
